update docs for 0.2.0
KempnerInstitute/tatm pull request #107
Opened 2024-12-19 21:44 UTC by mbsabath

closes #102 

Big blast of text, hope in going through this we find pain points or issues

2024-12-19 22:13 UTC, timothyngo requested changes
Looks fine, although in the future it would be good to have the code changes in a separate PR from the documentation/markdown changes.

Just need to correct the typo for `directories` and will approve.

2024-12-19 22:13 UTC, timothyngo commented on docs/admin_docs/metadata_store_setup.md
> +- `scripts/metadata/load_open_metadata_backend.py`: A script to load metadata into an OpenMetadata store. This script will parse a provided list of structured directories and load the metadata for ea
`directies` -> `directories`

2024-12-20 15:40 UTC, mbsabath commented on docs/admin_docs/metadata_store_setup.md
> +- `scripts/metadata/load_open_metadata_backend.py`: A script to load metadata into an OpenMetadata store. This script will parse a provided list of structured directories and load the metadata for ea
fixed!

2024-12-20 16:13 UTC, timothyngo approved these changes

2024-12-20 17:12 UTC, merged