Add basic image-text dataset code
KempnerInstitute/tatm pull request #98
Opened 2024-12-10 01:45 UTC by timothyngo

Closes #97 

This code adds very basic image-text dataset code. In particular, it adds the ability to read captioned images in the format used in LAVIS. Much of this code is still preliminary and undoubtedly things will changes as we see how code is structured in other libraries, but this is a launching point for future multimodal work.

2024-12-10 16:01 UTC, mbsabath requested changes
Like the direction things are going, have some concerns around how we're handling large dataset and maybe some thoughts around how we want to do abstraction

2025-01-04 00:10 UTC, timothyngo commented on src/tatm/data/datasets.py
> +import os.path
Done

2025-01-04 00:11 UTC, timothyngo commented on src/tatm/data/datasets.py
> +class TatmImageTextDataset(TatmDataset):
Discussed on zoom call. This is still part of the plan, just in a future PR.

2025-01-04 00:11 UTC, timothyngo commented on src/tatm/data/datasets.py
> +        image_path = os.path.join(self.img_root, ann["image"])
Changed

2025-01-04 00:12 UTC, timothyngo commented on src/tatm/data/datasets.py
> +                self.annotations.extend(json.load(f))
Discussed on zoom call, right now the datasets are too small where this is a concern, but the plan is to program things well so that it is easy to swap formats when we find it more optimal to do so, without exposing the internals to users.

2025-01-04 00:17 UTC, timothyngo commented on tests/data/multimodal/tatum.jpg
Added appropriate attribution for the CC image.

2025-01-06 20:28 UTC, mbsabath approved these changes
Given planned future changes, LGTM

2025-01-06 20:34 UTC, merged